name: Automatisation des tests

on: push

jobs:

  Compilation:
    runs-on: ubuntu-latest
    steps:
    
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Compilation du projet
        run: |
          mkdir build
          cd build
          cmake ..
          make
      
      
      - name: Sauvegarde de l'artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-build
          path: build/       

 
  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation 
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build

 
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator

      - name: Test fonction add
        run: ./src/calculator add 2 3

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build
      
   
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator
        
      - name: Test fonction sub
        run: ./src/calculator sub 3 -2

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build


      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator

      - name: Test fonction mul
        run: ./src/calculator mul 5 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build

    
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator

      - name: Test fonction div
        run: ./src/calculator div 1 5
  
  Test_Carre:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build

    
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator

      - name: Test fonction car
        run: ./src/calculator car 5


  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Carre]
    steps:
      - name: Déploiement de la solution
        run: echo "Tous les tests sont passés, déploiement réussi !"